### ISSUE TITLE
interaction of newline-and-indent with org-babel-edit-prep:jupyter-python

### ISSUE THREAD

**Issue by jkitchin** [nnicandro/emacs-jupyter#354]
I am not sure this is a bug, but it is undesired behavior for me. I have <RET> bound to `newline-and-indent` in src blocks. With emacs-jupyter, that leads to the kernel getting started when I press return in a src block.  This eventually is caused by `newline-and-indent` calling `ndent-according-to-mode`,  then `org-babel-do-key-sequence-in-edit-buffer`, then `org-edit-src-code`, which calls `org-babel-edit-prep:jupyter-python`, which starts the kernel when it isn't already running.

It seems like that should not happen, and the kernel should only be started when you decide to run the block.  I don't see a good solution, this seems like a side effect from `newline-and-indent`. Anyway, I thought I would report it and see what you think.

**Comment by nnicandro** [comment]
For the code paths going through `org-edit-src-code`, a kernel starts if not already because I wanted the REPL buffer to be associated with the edit buffer as part of the preparation. That association is useful for code completion and the like when editing the source code, but yes it doesn't matter much from the perspective of `org-babel-do-key-sequence-in-edit-buffer` when the edit buffer is not actively used by a user.

Maybe do something like make that association only when the kernel is already running? But it would be useful to start a kernel when the edit buffer is actually being used by a user. So if we went down this route we would have to distinguish between `org-edit-src-code` called interactively vs not.

Also conditionally making the association would only prevent starting kernels for the code paths going through `org-edit-src-code`. A kernel will also be launched if not already by just typing within the code block (to get kernel completions). I don't think that should be prevented. Also keybindings like `C-x C-e` on a line of a code block has the potential to start a kernel. Basically anything that calls `jupyter-org-with-src-block-client`.

Although it does make sense to start a kernel only when a user decides to run a block, starting kernels on demand is more convenient from a user perspective given all the actions that a user can take. Constraining when a kernel is started would prevent some of those actions from being made until after a block has been run.

**Comment by jkitchin** [comment]
These are all fair points. I can see benefits for on demand kernels. I am not sure how to detect the scenario I described to suppress it. Maybe it will grow on me. I will go ahead and close this, it seems like a preference issue.
