### ISSUE TITLE
Open REPL in vertical split

### ISSUE THREAD

**Issue by d-miketa** [nnicandro/emacs-jupyter#384]
Hi, thanks for the amazing package!

One thing I'd find useful (but should be easy to add) is the option to open REPL in a vertical rather than horizontal split. Perhaps as an optional argument to `jupyter-run-repl`?

**Comment by xor-xor** [comment]
This can be achieved by adding something like this to your config:
```elisp
(add-to-list 'display-buffer-alist
	     '("\\*jupyter-repl"
	       (display-buffer-in-direction)
	       (direction . right)))	; or 'left', if that's what you prefer
```
BTW, deciding where to display a newly-created buffer is a [rather complex subject in general](https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html), and a lot of this complexity depends on your initial situation (i.e. how many windows your current frame has, and how their layout looks like), so I think that customizing this behaviour via your config, instead of adding an extra argument to `jupyter-run-repl`, may be the optimal way to go here.

**Comment by d-miketa** [comment]
Thanks, appreciate the code snippet and explanation! :) I agree this is best left to the user.
